package co.uniquindio.edu.model.enums;

public enum TipoEspecializacion {

    MECANICA_GENERAL,
    ELECTRICIDAD_AUTOMOTRIZ,
    INYECCION_ELECTRONICA,
    FRENOS,
    SUSPENSION_Y_DIRECCION,
    TRANSMISION,
    AIRE_ACONDICIONADO,
    SISTEMA_DE_ENFRIAMIENTO,
    DIAGNOSTICO_COMPUTARIZADO,
    LATONERIA_Y_PINTURA,
    SISTEMA_DE_ESCAPE,
    MOTOR_GASOLINA,
    MOTOR_DIESEL,
    ELECTRONICA_DE_BORDO,
    ALINEACION_Y_BALANCEO
}
