### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

### ClientesController Endpoints

# Crear cliente (listo)
POST http://localhost:8080/api/clientes
Content-Type: application/json

{
  "nombre1": "ANDRES",
  "nombre2": "HUMBERTO",
  "apellido1": "Pérez",
  "apellido2": "Gómez",
  "email": "andres@gmail.com",
  "telefonos": [
    {
      "tipo": "CELULAR",
      "numero": "3001234567"
    }
  ],
  "direccion": "Calle 123",
  "barrio": "Centro",
  "ciudad": "armenia",
  "departamento": "quindio"
}

###

# Eliminar cliente (listo)
DELETE http://localhost:8080/api/clientes/a784f589-068e-4bb8-ab4a-b84e991902df
Content-Type: application/json

###

# Actualizar cliente (listo)
PUT http://localhost:8080/api/clientes/a784f589-068e-4bb8-ab4a-b84e991902df
Content-Type: application/json

{
  "nombre1": "SAMUEL",
  "nombre2": "Carlos",
  "apellido1": "Pérez",
  "apellido2": "Gómez",
  "email": "juan.perez@example.com",
  "telefonos": [
    {
      "tipo": "CELULAR",
      "numero": "3001234567"
    }
  ],
  "direccion": "Calle 123",
  "barrio": "Centro",
  "ciudad": "Bogotá",
  "departamento": "Cundinamarca"
}

###

# Obtener cliente (listo)
GET http://localhost:8080/api/clientes/8b060c32-c3e7-46ef-b163-9143c011aece

###

GET http://localhost:8080/api/clientes/all

###

# Listar órdenes por cliente (listo)
GET http://localhost:8080/api/clientes/f3be5f2d-8ebd-41dc-98b0-334f7c1b275d/ordenes

###

# Listar servicios y repuestos por vehículo del cliente
GET http://localhost:8080/api/clientes/{idCliente}/vehiculos/{placaVehiculo}/servicios-repuestos

###

### OrdenesController Endpoints

# Crear orden para un vehículo (listo)
POST http://localhost:8080/api/ordenes/f7dda9b4-a8de-487b-a1dd-f429393e6227/vehiculo
Content-Type: application/json

{
  "fechaIngreso": "2025-10-01T10:00:00",
  "descripcion": "El vehiculo llegó por ruidos extraños en el motor"
}

###

# Eliminar orden (listo)
DELETE http://localhost:8080/api/ordenes/7f1224ee-4db3-48de-824f-51665333e70e

###

# Actualizar orden (LISTO)
PUT http://localhost:8080/api/ordenes/b5d14bf4-29c9-47df-9295-b53502d67698
Content-Type: application/json

{
  "descripcion": "Cambio de aceite y filtros",
  "fechaIngreso": "2023-10-01T10:00:00",
  "fechaSalida": "2023-10-02T15:00:00"
}

###

# Obtener orden (listo)
GET http://localhost:8080/api/ordenes/b5d14bf4-29c9-47df-9295-b53502d67698

###

# Listar todas las órdenes (Listo)
GET http://localhost:8080/api/ordenes

###

# Asignar mecánico a orden (Listo)
PATCH http://localhost:8080/api/ordenes/b5d14bf4-29c9-47df-9295-b53502d67698/mecanicos/9953b337-6692-4a55-89b8-63baef20b18d
Content-Type: application/json

{
  "rol": "MECANICO"
}

###

# Eliminar mecánico de orden
DELETE http://localhost:8080/api/ordenes/{idOrden}/mecanicos/{idMecanico}

###

# Obtener mecánicos por orden (listo)
GET http://localhost:8080/api/ordenes/b5d14bf4-29c9-47df-9295-b53502d67698/mecanicos

###

# Registrar diagnóstico (listo)
POST http://localhost:8080/api/ordenes/b5d14bf4-29c9-47df-9295-b53502d67698/diagnosticos
Content-Type: application/json

{
  "diagnosticoInicial": "Problema en el motor",
  "diagnosticoFinal": "Problema del motor resuelto"
}

###

# Obtener diagnóstico (listo)
GET http://localhost:8080/api/ordenes/b5d14bf4-29c9-47df-9295-b53502d67698/diagnosticos

###

# Registrar servicio-Mecanico en orden (relación ternaria) (LISTO)
POST http://localhost:8080/api/ordenes/b5d14bf4-29c9-47df-9295-b53502d67698/mecanicos/9953b337-6692-4a55-89b8-63baef20b18d/servicios/68e245fc-0f0c-43ef-935f-f103127d5829
Content-Type: application/json

{
  "rol": "MECANICO",
  "horasTrabajadas": 2,
  "fechaAsignacion": "2023-10-01T10:00:00"
}

###

# Actualizar detalle de servicio-mecanico en la orden (LISTO)
PUT http://localhost:8080/api/ordenes/b5d14bf4-29c9-47df-9295-b53502d67698/mecanicos/9953b337-6692-4a55-89b8-63baef20b18d/servicios/68e245fc-0f0c-43ef-935f-f103127d5829
Content-Type: application/json

{
  "rol": "SUPERVISOR",
  "horasTrabajadas": 3,
  "fechaAsignacion": "2023-10-01T10:00:00"
}

###

# Obtener detalle de orden (LISTO)
GET http://localhost:8080/api/ordenes/b5d14bf4-29c9-47df-9295-b53502d67698/detalle

###

### FacturaController Endpoints

# Obtener factura por orden (falta)
GET http://localhost:8080/api/facturas/b5d14bf4-29c9-47df-9295-b53502d67698/ordenes

###

# Obtener facturas por placa de vehículo (falta)
GET http://localhost:8080/api/facturas/{placa}/vehiculos

###

# Listar todas las facturas (listo)
GET http://localhost:8080/api/facturas

###

# Obtener facturas por cliente (falta)
GET http://localhost:8080/api/facturas/8b060c32-c3e7-46ef-b163-9143c011aece/factura

###

### MecanicoController Endpoints

# Crear mecánico (LISTO)
POST http://localhost:8080/api/mecanicos
Content-Type: application/json

{
  "nombre1": "Pedro",
  "nombre2": "Antonio",
  "apellido1": "Rodríguez",
  "apellido2": "Martínez",
  "email": "pedro.rodriguez@example.com",
  "experiencia": 5,
  "salario": 200000,
  "especializacion": ["LATONERIA_Y_PINTURA"],
  "estado": "ACTIVO"
}

###

# Actualizar mecánico (LISTO)
PUT http://localhost:8080/api/mecanicos/6e393ee2-42b7-4c2e-b35c-8f5efdc1fa86
Content-Type: application/json

{
  "nombre1": "Pedro",
  "nombre2": "Antonio",
  "apellido1": "Rodríguez",
  "apellido2": "Martínez",
  "email": "pedro.rodriguez@example.com",
  "experiencia": 6,
  "especializacion": ["MECANICA_GENERAL"]
}

###

# Listar mecánicos (listo)
GET http://localhost:8080/api/mecanicos

###

# Obtener mecánico (listo)
GET http://localhost:8080/api/mecanicos/6e393ee2-42b7-4c2e-b35c-8f5efdc1fa86

###

# Eliminar mecánico (listo)
DELETE http://localhost:8080/api/mecanicos/6e393ee2-42b7-4c2e-b35c-8f5efdc1fa86

###

# Obtener estadísticas de mecánico (falta)
GET http://localhost:8080/api/mecanicos/675c3dea-21bd-4a83-9b91-63afdda88e0d/estadisticas

###

# Listar servicios por mecánico (falta)
GET http://localhost:8080/api/mecanicos/675c3dea-21bd-4a83-9b91-63afdda88e0d/servicios

###

### ProveedorController Endpoints

# Crear proveedor (listo)
POST http://localhost:8080/api/proveedores
Content-Type: application/json

{
  "nombre": "Proveedor ABC",
  "email": "contacto@proveedorabc.com",
  "telefonos": [
    {
      "tipo": "FIJO",
      "numero": "6012345678"
    }
  ]
}

###

# Actualizar proveedor (listo)
PUT http://localhost:8080/api/proveedores/ecb3d0ed-d275-4771-94a4-a93a19f71062
Content-Type: application/json

{
  "nombre": "SAamuel ABC",
  "email": "contacto@proveedorabc.com",
  "telefonos": [
    {
      "tipo": "FIJO",
      "numero": "6012345678"
    }
  ]
}

###

# Listar proveedores (listo)
GET http://localhost:8080/api/proveedores

###

# Obtener proveedor (LISTO)
GET http://localhost:8080/api/proveedores/ecb3d0ed-d275-4771-94a4-a93a19f71062

###

# Eliminar proveedor (listo)
DELETE http://localhost:8080/api/proveedores/02147681-9ee1-44f1-8b70-e9f960624fe1

###

### RepuestosController Endpoints

# Crear repuesto (listo)
POST http://localhost:8080/api/repuestos
Content-Type: application/json

{
  "nombre": "llanta",
  "costoUnitario": 15000.0,
  "stock": 50
}

###

# Actualizar repuesto (listo)
PUT http://localhost:8080/api/repuestos/ec235b5b-7bff-4e0f-b010-21bf6204cd99
Content-Type: application/json

{
  "nombre": "Filtro de aceite",
  "costoUnitario": 16000.0,
  "stock": 45
}

###

# Listar repuestos (listo)
GET http://localhost:8080/api/repuestos

###

# Obtener repuesto (listo)
GET http://localhost:8080/api/repuestos/ec235b5b-7bff-4e0f-b010-21bf6204cd99

###

# Eliminar repuesto (listo)
DELETE http://localhost:8080/api/repuestos/ec235b5b-7bff-4e0f-b010-21bf6204cd99

###

### ServiciosController Endpoints

# Crear servicio (LISTO)
POST http://localhost:8080/api/servicios
Content-Type: application/json

{
  "tipoServicio": "PINTURA",
  "descripcion": "Se pinta todo el vehiculo del color que el cliente desee",
  "costoUnitario": 1000000,
  "fechaCreacion": "2025-10-21"

}

###

# Actualizar servicio (listo)
PUT http://localhost:8080/api/servicios/35044ad5-57e8-4c31-9e2e-4dc747233002
Content-Type: application/json

{
  "tipoServicio": "ALINEACION_Y_BALANCEO",
  "descripcion": "ALINEACION A LAS LLANTAS",
  "costoUnitario": 100000.0
}

###

# Listar servicios (listo)
GET http://localhost:8080/api/servicios

###

# Obtener servicio (listo)
GET http://localhost:8080/api/servicios/06c720c2-dfc3-4655-8306-d32225327d9b

###

# Eliminar servicio (LISTO)
DELETE http://localhost:8080/api/servicios/06c720c2-dfc3-4655-8306-d32225327d9b

###

### VehiculosController Endpoints

# Crear vehículo para cliente (listo)
POST http://localhost:8080/api/vehiculos/f3be5f2d-8ebd-41dc-98b0-334f7c1b275d/clientes
Content-Type: application/json

{
  "placa": "ABC123",
  "anio": 2020,
  "color": "Blanco",
  "modelo": "gt3",
  "marca": "Porsche"
}

###

# Actualizar vehículo (listo)
PUT http://localhost:8080/api/vehiculos/d4941010-2051-4ccd-9bcc-3f1b186a0032/clientes/f3be5f2d-8ebd-41dc-98b0-334f7c1b275d
Content-Type: application/json

{
  "placa": "ABC123",
  "anio": 2023,
  "color": "Azul",
  "modelo": "Corolla",
  "marca": "Toyota"
}

###

# Listar vehículos (listo)
GET http://localhost:8080/api/vehiculos

###

# Obtener vehículo (listo)
GET http://localhost:8080/api/vehiculos/92385571-707c-44c7-b44f-3c71635a6953
###

# Eliminar vehículo (listo)
DELETE http://localhost:8080/api/vehiculos/d4941010-2051-4ccd-9bcc-3f1b186a0032

### REPORTES

# Reporte 1 simple (lista de todas las ordenes)
GET http://localhost:8080/api/reportes/ordenes/pdf

###

# Reporte 2 simple (lista de todos los repuestos disponibles)
GET http://localhost:8080/api/reportes/repuestos/pdf

###

// Reporte 3 simple (lista de todos los servicios disponibles del taller)
GET http://localhost:8080/api/reportes/servicios/pdf

###

// Reporte 4 Intermedio (lista de todos los mecanicos implicitos en una orden)
GET http://localhost:8080/api/reportes/mecanicos/b5d14bf4-29c9-47df-9295-b53502d67698/ordenes/pdf

###

// Reporte 5 Intermedio (lista de ordenes del cliente)
GET http://localhost:8080/api/reportes/ordenes/f3be5f2d-8ebd-41dc-98b0-334f7c1b275d/clientes/pdf

###